version: "2.1"

services:
  smart-postgres:
    image: arribada/smart-connect-postgis
    environment:
      POSTGRES_USER: $POSTGRES_USER # The username is also used for the db name.
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
    - smart-postgres:/var/lib/postgresql/data
  smart-connect:
    image: arribada/smart-connect
    depends_on:
      - smart-postgres
    ports:
    - "8443:8443"
    volumes:
    - smart-connect:/home/SMARTconnect/filestore/
    environment:
      POSTGRES_HOSTNAME: smart-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  lora-connect:
    image: arribada/lora-connect
    ports:
    - "8070:8070"

  packet-forwarder:
    image: arribada/packet-forwarder
    privileged: true
    environment:
      - PORT=8090 # The web port on which to show the gateway ID.
      - CONCENTRATOR_RESET_PIN=22
      - GW_HOST=gatewaybridge # Where to send the packets
    ports:
      - 8090:8090 
  loraserver:
    image: arribada/loraserver
    depends_on:
      - postgresql
# #     volumes:
# #       - ./loraserver-docker/configuration/loraserver:/etc/loraserver

  appserver:
    image: arribada/lora-app-server
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    # volumes:
    #   - ./loraserver-docker/configuration/lora-app-server:/etc/lora-app-server

  gatewaybridge:
    image: arribada/lora-gateway-bridge
    # ports:
    #   - 1700:1700/udp
#     volumes:
#       - ./loraserver-docker/configuration/lora-gateway-bridge:/etc/lora-gateway-bridge

  geoserver:
    image: arribada/lora-geo-server
#     volumes:
#       - ./loraserver-docker/configuration/lora-geo-server:/etc/lora-geo-server

  postgresql:
    image: arribada/loraserver-postgres
    volumes:
      - lora-postgres:/var/lib/postgresql/data
      # - ./loraserver-docker/configuration/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:5-alpine
    volumes:
      - lora-redis:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883

volumes:
  smart-postgres:
  smart-connect:
  lora-postgres:
  lora-redis:
