
version: 2.1

orbs:
  docker: arribada/docker@0.0.16
workflows:
  publish:
    jobs:
      - docker/publish:
          containerName: lora-gps-server
          buildContext: receiver/LoraToGPSServer
          context: org-context
          filters:
            branches:
                only:
                  - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/