version: "2.1"

services:
  env-to-file:
    image: arribada/envtofile:master
    volumes:
    - configs:/configs/
    command:
        - --dir=/configs/
    environment:
      # PROMETHEUS_CONFIG: |-
      #   global:
      #     scrape_interval:     5s
      #   scrape_configs:
      #     - job_name: 'lora-gps-server'
      #       static_configs:
      #       - targets: ['lora-gps-server:8070']
      #   alerting:
      #     alertmanagers:
      #     - static_configs:
      #       - targets:
      #           - alertmanager:9093
      #   rule_files:
      #       - /configs/PROMETHEUS_ALERTING
      # PROMETHEUS_ALERTING: |-
      #   groups:
      #   - name: /etc/prometheus/alert.rules
      #     rules:
      #     - alert: GPSNoUpdate
      #       expr: last_update_seconds>6000
      #       labels:
      #         severity: "critical"
      #       annotations:
      #         summary: \"GPS tracker hasn't sent data\"
      #     - alert: GPSPerimeterBreach
      #       expr: max_over_time(distance_meters[1m])>1000
      #       labels:
      #         severity: "critical"
      #       annotations:
      #         summary: \"GPS tracker parameter threshold\"
      # ALERTMANAGER_CONFIG: |-
      #   route:
      #     receiver: 'default'
      #     routes:
      #     - match:
      #           alertname: GPSPerimeterBreach
      #     - match:
      #           alertname: GPSNoUpdate
      #   receivers:
      #   - name: 'default'
      #     pagerduty_configs:
      #     - routing_key: $PAGERDUTY_ROUTING_KEY
      #     slack_configs:
      #       - api_url: $SLACK_API_URL
      #         send_resolved: true
      mosquitto_conf: |-
        listener 1883
        allow_anonymous true
      INIT_CHIRPSTACK_sh: |-
        #!/bin/bash
        set -e

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          create role chirpstack_ns with login password '$POSTGRES_PASSWORD';
          create database chirpstack_ns with owner chirpstack_ns;
        EOSQL

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          create role chirpstack_as with login password '$POSTGRES_PASSWORD';
          create database chirpstack_as with owner chirpstack_as;
        EOSQL

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack_as" <<-EOSQL
          create extension pg_trgm;
        EOSQL

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack_as" <<-EOSQL
          create extension hstore;
        EOSQL
      TRACCAR_xml: |-
        <?xml version='1.0' encoding='UTF-8'?>

        <!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

        <properties>

            <entry key='config.default'>./conf/default.xml</entry>

            <entry key='database.driver'>org.h2.Driver</entry>
            <entry key='database.url'>jdbc:h2:./data/database</entry>
            <entry key='database.user'>sa</entry>
            <entry key='database.password'></entry>
            <entry key='logger.file'>/dev/stdout</entry>
            <entry key='logger.level'>info</entry>
            <entry key='report.trip.minimalNoDataDuration'>1</entry>
            <entry key='report.trip.minimalTripDuration'>1</entry>
            <entry key='report.trip.minimalTripDistance'>1</entry>
            <entry key='report.trip.minimalParkingDuration'>1</entry>
        </properties>

### Rpi Lora Hat
  # packet-forwarder:
  #   image: arribada/packet-forwarder@sha256:7ea7afe7ecc5080be0e882e3f310c373bd8a29503c6c647063fad40ba7d76d60
  #   privileged: true
  #   environment:
  #     CONCENTRATOR_RESET_PIN: 22
  #     CONCENTRATOR_CONFIG: |-
  #       {
  #         "SX1301_conf": {
  #             "lorawan_public": true,
  #             "clksrc": 1,
  #             "antenna_gain": 0,
  #             "radio_0": {
  #                 "enable": true,
  #                 "type": "SX1257",
  #                 "freq": 867500000,
  #                 "rssi_offset": -166.0,
  #                 "tx_enable": true,
  #                 "tx_freq_min": 863000000,
  #                 "tx_freq_max": 870000000
  #             },
  #             "radio_1": {
  #                 "enable": true,
  #                 "type": "SX1257",
  #                 "freq": 868500000,
  #                 "rssi_offset": -166.0,
  #                 "tx_enable": false
  #             },
  #             "chan_multiSF_0": {
  #                 "enable": true,
  #                 "radio": 1,
  #                 "if": -400000
  #             },
  #             "chan_multiSF_1": {
  #                 "enable": true,
  #                 "radio": 1,
  #                 "if": -200000
  #             },
  #             "chan_multiSF_2": {
  #                 "enable": true,
  #                 "radio": 1,
  #                 "if": 0
  #             },
  #             "chan_multiSF_3": {
  #                 "enable": true,
  #                 "radio": 0,
  #                 "if": -400000
  #             },
  #             "chan_multiSF_4": {
  #                 "enable": true,
  #                 "radio": 0,
  #                 "if": -200000
  #             },
  #             "chan_multiSF_5": {
  #                 "enable": true,
  #                 "radio": 0,
  #                 "if": 0
  #             },
  #             "chan_multiSF_6": {
  #                 "enable": true,
  #                 "radio": 0,
  #                 "if": 200000
  #             },
  #             "chan_multiSF_7": {
  #                 "enable": true,
  #                 "radio": 0,
  #                 "if": 400000
  #             },
  #             "chan_Lora_std": {
  #                 "enable": true,
  #                 "radio": 1,
  #                 "if": -200000,
  #                 "bandwidth": 250000,
  #                 "spread_factor": 7
  #             },
  #             "chan_FSK": {
  #                 "enable": true,
  #                 "radio": 1,
  #                 "if": 300000,
  #                 "bandwidth": 125000,
  #                 "datarate": 50000
  #             },
  #             "tx_lut_0": {
  #                 "pa_gain": 0,
  #                 "mix_gain": 8,
  #                 "rf_power": -6,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_1": {
  #                 "pa_gain": 0,
  #                 "mix_gain": 10,
  #                 "rf_power": -3,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_2": {
  #                 "pa_gain": 0,
  #                 "mix_gain": 12,
  #                 "rf_power": 0,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_3": {
  #                 "pa_gain": 1,
  #                 "mix_gain": 8,
  #                 "rf_power": 3,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_4": {
  #                 "pa_gain": 1,
  #                 "mix_gain": 10,
  #                 "rf_power": 6,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_5": {
  #                 "pa_gain": 1,
  #                 "mix_gain": 12,
  #                 "rf_power": 10,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_6": {
  #                 "pa_gain": 1,
  #                 "mix_gain": 13,
  #                 "rf_power": 11,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_7": {
  #                 "pa_gain": 2,
  #                 "mix_gain": 9,
  #                 "rf_power": 12,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_8": {
  #                 "pa_gain": 1,
  #                 "mix_gain": 15,
  #                 "rf_power": 13,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_9": {
  #                 "pa_gain": 2,
  #                 "mix_gain": 10,
  #                 "rf_power": 14,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_10": {
  #                 "pa_gain": 2,
  #                 "mix_gain": 11,
  #                 "rf_power": 16,
  #                 "dig_gain": 0
  #             },
  #             "tx_lut_11": {
  #                 "pa_gain": 3,
  #                 "mix_gain": 9,
  #                 "rf_power": 20,
  #                 "dig_gain": 0
  #             }
  #         },

  #         "gateway_conf": {
  #             "gateway_ID": "0242acfffe110006",
  #             "server_address": "chirpstack-gatewaybridge",
  #             "serv_port_up": 1700,
  #             "serv_port_down": 1700,
  #             "keepalive_interval": 10,
  #             "stat_interval": 30,
  #             "push_timeout_ms": 100,
  #             "forward_crc_valid": true,
  #             "forward_crc_error": false,
  #             "forward_crc_disabled": false,
  #             "beacon_period": 128,
  #             "beacon_freq_hz": 869525000,
  #             "beacon_datarate": 9,
  #             "beacon_bw_hz": 125000,
  #             "beacon_power": 14,
  #             "beacon_infodesc": 0
  #         }
  #       }

### Chirpstack containers.
  # chirpstack-gatewaybridge: # When using lorix it runs directly on the Lorix OS so not needed.
  #   image: chirpstack/chirpstack-gateway-bridge:3.13.0-test.2
  #   ports:
  #     - 1700:1700/udp
  #   environment:
  #     - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://chirpstack-mosquitto:1883

  chirpstack-networkserver:
    image: chirpstack/chirpstack-network-server:3.15.0-test.2
    environment:
      - REDIS__URL=redis://chirpstack-redis:6379
      - NETWORK_SERVER__BAND__NAME=EU_863_870
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://chirpstack-mosquitto:1883
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-appserver:8003
      - GEOLOCATION_SERVER__SERVER=chirpstack-geoserver:8005
  chirpstack-appserver:
    image: chirpstack/chirpstack-application-server:3.17.0-test.2
    ports:
      - 8080:8080
    environment:
      - REDIS__URL=redis://chirpstack-redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://chirpstack-mosquitto:1883
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-appserver:8001

  chirpstack-postgresql:
    depends_on:
      - env-to-file
    image: postgres:9.6-alpine
    volumes:
      - configs:/docker-entrypoint-initdb.d/
      - chirpstack-postgres:/var/lib/postgresql/data
  chirpstack-redis:
    image: redis:6.2.5-alpine
    volumes:
      - chirpstack-redis:/data
  chirpstack-mosquitto:
    ports:
      - 1883:1883
    image: eclipse-mosquitto:2.0.11
    volumes:
      - configs:/mosquitto/config/

  # smart-postgres:
  #   image: arribada/smart-connect-postgis@sha256:96787a45e1146ac3cd88cad15aa89243d74738e574e6b9730a07415616e3e521
  #   volumes:
  #   - smart-postgres:/var/lib/postgresql/data
  # smart-connect:
  #   image: arribada/smart-connect@sha256:da4b79c840bd354d8ccf1d6afe94eefe8fa64bc561f110a3d7684add6b0c4709
  #   ports:
  #   - "8443:8443"
  #   volumes:
  #   - smart-connect:/home/SMARTconnect/filestore/
  #   environment:
  #     POSTGRES_HOSTNAME: smart-postgres
  #     POSTGRES_PORT: 5432
  # prometheus:
  #   image: prom/prometheus@sha256:ac56e023deb66f2bf25fe103db8c96b927c68239008ac221670b27e9ea4e3956
  #   volumes:
  #   - configs:/configs/
  #   - prometheus:/prometheus
  #   ports:
  #     - 9090:9090
  #   command:
  #   - --config.file=/configs/PROMETHEUS_CONFIG
  #   - --storage.tsdb.retention.size=10GB
  # alertmanager:
  #   image: prom/alertmanager@sha256:090ffef59d4089b7ff9fba475f3c0bb8e2ceb7351483a054c02fb29c8e004709
  #   volumes:
  #   - configs:/configs/
  #   - alertmanager:/alertmanager
  #   ports:
  #     - 9093:9093
  #   command:
  #     - --config.file=/configs/ALERTMANAGER_CONFIG

  traccar:
    image: traccar/traccar:4.14-ubuntu
    volumes:
    - configs:/configs/
    - traccar-database:/opt/traccar/data
    ports:
      - 80:8082
      - 5055:5055
    command:
     - -jar
     - tracker-server.jar
     - /configs/TRACCAR.xml
  lora-gps-server:
    image: arribada/lora-gps-server:master
    ports:
    - "8070:8070"


volumes:
  # smart-postgres:
  # smart-connect:
  chirpstack-postgres:
  chirpstack-redis:
  # prometheus:
  # alertmanager:
  traccar-database:
  configs:
