version: "2.1"

services:
  env-config:
    image: arribada/env-config@sha256:63cc992847d8e378190d88dc21390f09337fd1102ccdb65d9aefd26846444b61
    volumes:
    - configs:/configs/
    command:
        - --dir=/configs/
    environment:
      PROMETHEUS__CONFIG: |-
        global:
          scrape_interval:     5s
        scrape_configs:
          - job_name: 'lora-connect'
            static_configs:
            - targets: ['lora-connect:8070']
        alerting:
          alertmanagers:
          - static_configs:
            - targets:
                - alertmanager:9093
        rule_files:
            - /configs/PROMETHEUS_ALERTING
      PROMETHEUS__ALERTING: |-
        groups:
        - name: /etc/prometheus/alert.rules
          rules:
          - alert: GPSNoUpdate
            expr: last_update_seconds>6000
            labels:
              severity: "critical"
            annotations:
              summary: \"GPS tracker hasn't sent data\"
          - alert: GPSPerimeterBreach
            expr: max_over_time(distance_meters[1m])>1000
            labels:
              severity: "critical"
            annotations:
              summary: \"GPS tracker parameter threshold\"
      ALERTMANAGER__CONFIG: |-
        route:
          receiver: 'krasi'
          routes:
          - match:
                alertname: GPSPerimeterBreach
          - match:
                alertname: GPSNoUpdate
        receivers:
        - name: 'krasi'
          pagerduty_configs:
          - routing_key: $ROUTING_KEY
      INIT__LORASERVER_sh: |-
        #!/bin/bash
        set -e

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          create role loraserver_ns with login password '$POSTGRES_PASSWORD';
          create database loraserver_ns with owner loraserver_ns;
        EOSQL

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          create role loraserver_as with login password '$POSTGRES_PASSWORD';
          create database loraserver_as with owner loraserver_as;
        EOSQL

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="loraserver_as" <<-EOSQL
          create extension pg_trgm;
        EOSQL

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="loraserver_as" <<-EOSQL
          create extension hstore;
        EOSQL
  smart-postgres:
    image: arribada/smart-connect-postgis@sha256:96787a45e1146ac3cd88cad15aa89243d74738e574e6b9730a07415616e3e521
    volumes:
    - smart-postgres:/var/lib/postgresql/data
  smart-connect:
    image: arribada/smart-connect@sha256:da4b79c840bd354d8ccf1d6afe94eefe8fa64bc561f110a3d7684add6b0c4709
    ports:
    - "8443:8443"
    volumes:
    - smart-connect:/home/SMARTconnect/filestore/
    environment:
      POSTGRES_HOSTNAME: smart-postgres
      POSTGRES_PORT: 5432
  lora-connect:
    image: arribada/lora-connect@sha256:150debfe7bf63e854861316eddbfcdff34b85973ab02c89a79ad0365e40085ac
    # ports:
    # - "8070:8070"
  packet-forwarder:
    image: arribada/packet-forwarder@sha256:899d4fe181c785a376ea9c441e5220f4256966012a5f8ce9a194a7a983ce170e
    depends_on:
      - gatewaybridge
    privileged: true
    environment:
      CONCENTRATOR_RESET_PIN: 22
      CONCENTRATOR_CONFIG: |-
        {
          "SX1301_conf": {
              "lorawan_public": true,
              "clksrc": 1,
              "antenna_gain": 0,
              "radio_0": {
                  "enable": true,
                  "type": "SX1257",
                  "freq": 867500000,
                  "rssi_offset": -166.0,
                  "tx_enable": true,
                  "tx_freq_min": 863000000,
                  "tx_freq_max": 870000000
              },
              "radio_1": {
                  "enable": true,
                  "type": "SX1257",
                  "freq": 868500000,
                  "rssi_offset": -166.0,
                  "tx_enable": false
              },
              "chan_multiSF_0": {
                  "enable": true,
                  "radio": 1,
                  "if": -400000
              },
              "chan_multiSF_1": {
                  "enable": true,
                  "radio": 1,
                  "if": -200000
              },
              "chan_multiSF_2": {
                  "enable": true,
                  "radio": 1,
                  "if": 0
              },
              "chan_multiSF_3": {
                  "enable": true,
                  "radio": 0,
                  "if": -400000
              },
              "chan_multiSF_4": {
                  "enable": true,
                  "radio": 0,
                  "if": -200000
              },
              "chan_multiSF_5": {
                  "enable": true,
                  "radio": 0,
                  "if": 0
              },
              "chan_multiSF_6": {
                  "enable": true,
                  "radio": 0,
                  "if": 200000
              },
              "chan_multiSF_7": {
                  "enable": true,
                  "radio": 0,
                  "if": 400000
              },
              "chan_Lora_std": {
                  "enable": true,
                  "radio": 1,
                  "if": -200000,
                  "bandwidth": 250000,
                  "spread_factor": 7
              },
              "chan_FSK": {
                  "enable": true,
                  "radio": 1,
                  "if": 300000,
                  "bandwidth": 125000,
                  "datarate": 50000
              },
              "tx_lut_0": {
                  "pa_gain": 0,
                  "mix_gain": 8,
                  "rf_power": -6,
                  "dig_gain": 0
              },
              "tx_lut_1": {
                  "pa_gain": 0,
                  "mix_gain": 10,
                  "rf_power": -3,
                  "dig_gain": 0
              },
              "tx_lut_2": {
                  "pa_gain": 0,
                  "mix_gain": 12,
                  "rf_power": 0,
                  "dig_gain": 0
              },
              "tx_lut_3": {
                  "pa_gain": 1,
                  "mix_gain": 8,
                  "rf_power": 3,
                  "dig_gain": 0
              },
              "tx_lut_4": {
                  "pa_gain": 1,
                  "mix_gain": 10,
                  "rf_power": 6,
                  "dig_gain": 0
              },
              "tx_lut_5": {
                  "pa_gain": 1,
                  "mix_gain": 12,
                  "rf_power": 10,
                  "dig_gain": 0
              },
              "tx_lut_6": {
                  "pa_gain": 1,
                  "mix_gain": 13,
                  "rf_power": 11,
                  "dig_gain": 0
              },
              "tx_lut_7": {
                  "pa_gain": 2,
                  "mix_gain": 9,
                  "rf_power": 12,
                  "dig_gain": 0
              },
              "tx_lut_8": {
                  "pa_gain": 1,
                  "mix_gain": 15,
                  "rf_power": 13,
                  "dig_gain": 0
              },
              "tx_lut_9": {
                  "pa_gain": 2,
                  "mix_gain": 10,
                  "rf_power": 14,
                  "dig_gain": 0
              },
              "tx_lut_10": {
                  "pa_gain": 2,
                  "mix_gain": 11,
                  "rf_power": 16,
                  "dig_gain": 0
              },
              "tx_lut_11": {
                  "pa_gain": 3,
                  "mix_gain": 9,
                  "rf_power": 20,
                  "dig_gain": 0
              }
          },

          "gateway_conf": {
              "gateway_ID": "0242acfffe110006",
              "server_address": "gatewaybridge",
              "serv_port_up": 1700,
              "serv_port_down": 1700,
              "keepalive_interval": 10,
              "stat_interval": 30,
              "push_timeout_ms": 100,
              "forward_crc_valid": true,
              "forward_crc_error": false,
              "forward_crc_disabled": false,
              "beacon_period": 128,
              "beacon_freq_hz": 869525000,
              "beacon_datarate": 9,
              "beacon_bw_hz": 125000,
              "beacon_power": 14,
              "beacon_infodesc": 0
          }
        }
  loraserver:
    image: arribada/loraserver@sha256:99051299b1a734a1b56093336f0f2fd3b0db6672fe562a2ff5c9363453f9bfaa
    depends_on:
      - postgresql
      - mosquitto
    environment:
      - REDIS_URL=redis://redis:6379
      - NETWORK__SERVER_BAND_NAME=EU_863_870
      - NETWORK__SERVER_GATEWAY_BACKEND_MQTT_SERVER=tcp://mosquitto:1883
      - JOIN__SERVER_DEFAULT_SERVER=http://appserver:8003
      - GEOLOCATION__SERVER_SERVER=geoserver:8005
  appserver:
    image: arribada/lora-app-server@sha256:31878520b836fd78d340a94d90fab1318a790c21b5dbd657f4bbf66e5b5f3db6
    depends_on:
      - postgresql
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://redis:6379
      - APPLICATION__SERVER_INTEGRATION_MQTT_SERVER=tcp://mosquitto:1883
      - APPLICATION__SERVER_API_PUBLIC__HOST=appserver:8001
      
  gatewaybridge:
    image: arribada/lora-gateway-bridge@sha256:eeb2a0d12e2ba706d8dd071938fd3e0d8a7b06254d0748a7504c781b5425af9c
    depends_on:
      - mosquitto
    ports:
      - 1700:1700/udp
    environment:
      - INTEGRATION_MQTT_AUTH_GENERIC_SERVER=tcp://mosquitto:1883
  geoserver:
    image: arribada/lora-geo-server@sha256:69534b499347edfba84b2dd778993d3c0de83e435454737501d76cc300cf8249
    environment:
      - GEO__SERVER_BACKEND_NAME=collos
  postgresql:
    depends_on:
      - env-config
      - mosquitto
    image: postgres:9.6-alpine@sha256:5f30f64d292adba6834c2acf431660c41514a4bdf3b979e6dd2f9930dcf53175
    volumes:
      - configs:/docker-entrypoint-initdb.d/
      - lora-postgres:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine@sha256:f56ac9669267aec516ebfb8d7f61fc6344b7c93d9b24f45e0f952c6f74f36015
    volumes:
      - lora-redis:/data
  mosquitto:
    image: eclipse-mosquitto@sha256:98b755512a8487877e2e98cbf3ba7a4987bc71d8e1c632d5aa86f43ee7db0e34

  prometheus:
    image: prom/prometheus@sha256:ac56e023deb66f2bf25fe103db8c96b927c68239008ac221670b27e9ea4e3956
    depends_on:
      - env-config
    volumes:
    - configs:/configs/
    - prometheus:/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/configs/PROMETHEUS_CONFIG
  alertmanager:
    image: prom/alertmanager@sha256:090ffef59d4089b7ff9fba475f3c0bb8e2ceb7351483a054c02fb29c8e004709
    depends_on:
      - env-config
    volumes:
    - configs:/configs/
    - alertmanager:/alertmanager
    ports:
      - 9093:9093
    command:
      - --config.file=/configs/ALERTMANAGER_CONFIG

volumes:
  smart-postgres:
  smart-connect:
  lora-postgres:
  lora-redis:
  prometheus:
  alertmanager:
  configs:
